export { default as AllProducts } from "./AllProducts";
export { default as Contact } from "./Contact";
export { default as Home } from "./Home";
export { default as PageNotFound } from "./PageNotFound";
export { default as ProductCategory } from "./ProductCategory";
export { default as ProductDetails } from "./ProductDetails";
export { default as Cart } from "./Cart";
export { default as AddAddress } from "./AddAddress";
export { default as MyOrders } from "./MyOrders";
